### ISSUE TITLE
Feral Interactive games wont start with ckb-next [Bug report]

### ISSUE THREAD

**Issue by unelsson** [ckb-next/ckb-next#102]
"Segfault 11" results when running games like DiRT Rally or Total War Shogun 2. I'm Running Linux Manjaro 4.9.81-1-MANJARO x86_64 GNU/Linux. Manjaro is based on Arch linux. My keyboard is Corsair Strafe RGB. Problem is solved by disabling ckb-next daemon.

I don't know why this happens, and whether or not this is more of Feral's problem or a bug in ckb-next. I'll report this to feral interactive too.

**Comment by tatokis** [comment]
@unelsson Unfortunately, this one is probably on their end.
Assuming you have the udev rule that marks ckb-daemon devices as non-joysticks, there is probably not much we can do.

Would you mind linking to the feral bug report so that we can follow it?

I might install Tomb Raider and try it, but again, I doubt much can be done.

**Comment by ZirconiumX** [comment]
Should we close this? We have no upstream bug to track, and we cant do anything on our end.
