### ISSUE TITLE
Cmake error cant install.

### ISSUE THREAD

**Issue by SeyedDev** [ckb-next/ckb-next#151]
Terminal output

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.7.4") 
    Git directory to deduce precise version has not been not found.
    Consider cloning the project with git instead of downloading an archive.
    For example:
        git clone -b master --single-branch https://github.com/ckb-next/ckb-next.git
-- ckb-next version: 0.3.0-unknown (Non-release)
-- Performing Test C_COMPILER_SUPPORTS_-Og
-- Performing Test C_COMPILER_SUPPORTS_-Og - Success
-- Performing Test CXX_COMPILER_SUPPORTS_-Og
-- Performing Test CXX_COMPILER_SUPPORTS_-Og - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/lib/x86_64-linux-gnu/libc.so
-- Checking for module 'libudev'
--   Found libudev, version 229
-- Found UDEV: /usr/lib/x86_64-linux-gnu/libudev.so  
-- Searching for running ckb and/or ckb-next GUI
-- NOTE:
    Privileged access is required for operations upon the daemon at
    configure time as it is owned by root. If this is unacceptable,
    disable SAFE_INSTALL and prepare the filesystem manually.
-- upstart detected
-- Generating and importing ckb-next-daemon.conf (upstart)
[sudo] password for seyed: 
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
-- systemd detected
-- Generating and importing ckb-next-daemon.service (systemd)
inactive
Failed to get unit file state for ckb-daemon.service: No such file or directory
inactive
Failed to get unit file state for ckb-next-daemon.service: No such file or directory
-- Could NOT find QuaZip (missing:  QuaZip_LIBRARIES QuaZip_INCLUDE_DIR QuaZip_ZLIB_INCLUDE_DIR QuaZip_INCLUDE_DIRS) 
CMake Warning at src/libs/CMakeLists.txt:36 (message):
  Quazip was not found.  Using bundled version.

CMake Error at src/libs/quazip/CMakeLists.txt:35 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/seyed/Schreibtisch/ckb-next-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/seyed/Schreibtisch/ckb-next-master/build/CMakeFiles/CMakeError.log".
An error occurred,
press enter to exit.

**Comment by SeyedDev** [comment]
Thank you so much mate it works now :)

**Comment by OvermindDL1** [comment]
You know, instead of relying on a system-installed version of (potentially old version of) Qt5, why not add the hunter pure-cmake dependency manager to this project instead as it has [Qt5](https://docs.hunter.sh/en/latest/packages/pkg/Qt.html) listed in it's primary repository?  Only real changes needed to this project then would just be to copy the [HunterGate.cmake](https://raw.githubusercontent.com/hunter-packages/gate/master/cmake/HunterGate.cmake) file into the `cmake` directory then just add something like this to the root CMakeLists.txt file:

```cmake
# include the huntergate file to bootstrap the dependency manager:
include("cmake/HunterGate.cmake")

# Include the primary repository (can make your own and/or include others too):
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.20.41.tar.gz"
    SHA1 "e8e77b69fc2ca66808091e781cc06bcb02724443"
)

# Tell the dependency manager what dependencies we want to bring in, it will be
# version-locked by default based on the HunterGate repo's included, but can
# specify a version manually as well, however using the latest based on the above
# defined repo is fine here:
hunter_add_package(Qt) # Can add components of Qt here too if any are needed

# Everything else is just as normal, hunter will make sure Qt is compiled with the
# right setup and you just link it in as normal...  Hunter will cache the build as
# well.

find_package(Qt5Core REQUIRED)
find_package(Qt5Gui REQUIRED)
# Or whatever else, this code should already exist though so nothing special
```

**Comment by ZirconiumX** [comment]
@tatokis proposed having the `quickinstall` script check for `cmake` failure and then suggest an appropriate package manager command.

**Comment by OvermindDL1** [comment]
> appropriate package manager command.

Even then that assumes they are not using a package manager that contains a Qt5 version that is 'too old'.  Having dependencies at the system level means that potentially some bug reports are just because of mis-matched QT5 versions.

**Comment by ZirconiumX** [comment]
It [won't configure](https://github.com/ckb-next/ckb-next/blob/9ac819ef86290572f139039c414214cb68f071bc/src/gui/CMakeLists.txt#L72) with an unsupported Qt5 version.

**Comment by tatokis** [comment]
@OvermindDL1 Not using the version of Qt that ships with the distro is a bad idea for multiple reasons.

One of them would be the fact that distros ship Qt with plugins and/or patches to better integrate it (see appmenu-qt5).

Qt plugins in general are version-dependent, and you even get a nice warning about it when compiling them, so if a user has a local plugin they wish to use (such as qt5ct) that's built against the system version of Qt, it will be unusable.

Since platform themes are also plugins, they are also built against specific versions of Qt, so by doing that you'd be discarding local theming engines, as they will be incompatible with the new Qt libraries.

Sometimes older versions are preferred too. In this case, Qt 5.7 and higher obliterated the gtk platform theme, requiring people to use qt5ct if they want to get a gui that doesn't look ugly and horribly out of place.
Since I am running Ubuntu 16.04 that ships with Qt 5.5, I do not have to deal with manually loading and compiling appmenu-qt5 or adding a gtk theme, just to get the GUI to integrate better with the environment.

If there is some issue with a specific version of Qt that a distro ships with, we should only provide steps on how to work around it. If the users want it fixed, they should open a bug on the appropriate distro bug tracker and go from there.

To finish this off, the least officially tested and supported version of Qt is 5.2.
Ubuntu 14.04 ships with that, and it's a 4(!) year old release at this point.

@ZirconiumX pointed out a few parts of the code that indicate there might be support for Qt < 5.2, so if someone wants to try it, they can just stub/lower the check in cmake and report back if it works or not.

**Comment by OvermindDL1** [comment]
Been less of an issue for me I guess as I tend to run the latest stable KDE frameworks (and eschew GTK because ew... for a variety of reasons...)

But still, if building QT directly and using a recent version it should still work just fine regardless.  Although I'd opt for the kde framework in any case as it adds so many useful things to Qt, especially in regards to interactions (even with GTK environments).

And wow, Qt 5.2 is old... no one should still be using that, it had many issues...

**Comment by tatokis** [comment]
@OvermindDL1 We're not targetting any DE specifically, and I don't think anyone in the dev team runs anything related to KDE, so there's your answer I guess.

**Comment by OvermindDL1** [comment]
KDE's framework is not the Desktop Environment (which is Plasma), it's a set of helpers, libraries, and frameworks for building multi-platform Qt apps (including to Windows, anything built purely with the KDE Framework should be able to be built and run on any DE, on Linux, mac, Windows, Android, iOS, and elsewhere).

**Comment by tatokis** [comment]
@OvermindDL1 I know what it is, but it brings in tons of KDE dependencies, that are typically found installed on KDE desktops.

**Comment by tatokis** [comment]
As a sidenote, even KDE has its own Qt platform theme plugin.
Either way, to end this conversation, I am not adding Qt or any other library through a package manager to cmake.

If someone wants, they can get their own version of Qt and do whatever they want.
If anything, it would've been nice if cmake didn't spew annoying error messages that vaguely tell what the problem is to someone who is unfamiliar with the build system.
Since that's unlikely to change, I think adding a message in quickinstall or maybe cmake itself, but in bold or highlighted, linking to the wiki page with the dependencies will be good enough.

KF5 may be something to look into in the future, but I really doubt it is going to help much as it is.

**Comment by OvermindDL1** [comment]
> maybe cmake itself

Instead of having a required find for Qt, make it not required and test if it found it, if not then print an appropriate message (perhaps even for the platform).
