### ISSUE TITLE
CKB doesn't recognize ALT key on K70 RGB

### ISSUE THREAD

**Issue by niklasbeab** [ckb-next/ckb-next#157]
Im on high sierra, and my ALT key is not recognized by the software. I tried to map different functions to the key but not a single one worked in some way.
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/1927806/ckb-next-dev-detect-report.gz)

**Comment by tatokis** [comment]
Can you control the light on the Alt key? Is it the left or the right alt? What's the keyboard layout? Have you picked the right layout from the device settings?

**Comment by niklasbeab** [comment]
Lightning is controllable on the key, yes. Actually both alt keys doesn't seem to work, left nor right.

Im using the german keyboard layout which is also selected in the device settings.

**Comment by niklasbeab** [comment]
Just noticed and i feel kinda dumb right now HAHA: I meant the windows keys, not the alt keys.

**Comment by ZirconiumX** [comment]
Can you [join us in IRC?](http://webchat.freenode.net/?channels=%23ckb-next&uio=d4)

**Comment by niklasbeab** [comment]
Sure

**Comment by niklasbeab** [comment]
[PLISTS.zip](https://github.com/ckb-next/ckb-next/files/1932308/PLISTS.zip)

All .plist files from the preference folder :)

**Comment by niklasbeab** [comment]
[BROKEN.zip](https://github.com/ckb-next/ckb-next/files/1932319/BROKEN.zip)

The broken profile

Profil called "Profi 1"

**Comment by tatokis** [comment]
@niklasbeab I had a look, and I think I see the issue here.
My guess is you accidentally pressed the winlock button, which disables the windows/super key.
After importing your profile and turning off winlock, the keys started working again.

If you still have the broken profile, switch to it and press the winlock button. It's the one on the top, to the right of the brightness button that has the windows logo inside a lock.
