### ISSUE TITLE
Problem with daemon and passing USB device to VM

### ISSUE THREAD

**Issue by GloriousEggroll** [ckb-next/ckb-next#264]
I've been using ckb-next for the past few months, and every time I go to pass through my keyboard and mouse to a virtual machine, I have to stop ckb-next before starting the VM, otherwise it tries to reclaim the devices and they never get passed to the VM.

For example my mouse will disconnect for a moment as it tries to pass to the vm, then it reconnects to the host instead.

A good example may be to have a look at libratbag - as it also runs as a daemon, but has no issues with passing logitech devices to a vm and reclaiming them after the vm closes. Typically you use libratbag with piper as the front end gui.

Devices:
K70 LUX RGB
Scimitar MMO Mouse

System:
Arch Linux
4.18 Kernel
TR 1950x Cpu

I've also tried this on multiple intel and ryzen systems as I travel often with my KB and mouse and smaller /mobile systems

**Comment by ZirconiumX** [comment]
If you need to use a VM, then stopping and starting the daemon is the
easiest way, although I question why you're passing through the USB devices
themselves and not using a virtual device provided by VirtualBox or QEMU.

Here's the thing: ratbag has an entirely different driver model compared to
us.

For Logitech devices, the Linux kernel talks to the device through the
hid-logitech-hidpp module, and so when you want to pass through the device,
hid-logitech-hidpp detaches itself from the device and hands it over to the
VM, pretty colours intact. This works because Logitech's protocol is
persistent, and so ratbag only has to talk to the device when it needs to
change the colour.

On Corsair devices, the situation is not so convenient; we have to take
control of the device ourselves because the protocol is stateless, and it
has a proprietary HID format for things like keypresses that would confuse
the kernel. An approach like that is awkward for situations like yours, but
for (buggy)  devices like the Glaive, it's the only way to make them work.

**Comment by GloriousEggroll** [comment]
Ah I see, this is understandable. I pass the device through because I run a gpu passthrough setup for native performance and virtual device latency is not decent enough for gaming. I am unable to pass the entire usb controller through because I have a large amount of USB devices connected to the controller (including already using a hub and a pci card). 

I was not aware that logitech used its own kernel module, which indeed does make things easier on that front.  I'll attempt to pass the entire controller through as a test to see if that helps with passing it through without starting/stopping the service.

thanks for the input
