### ISSUE TITLE
keypresses not recognized during system boot (alt)

### ISSUE THREAD

**Issue by mattbehnken** [ckb-next/ckb-next#275]
# Something else

after booting imac, holding "alt" key not recognized by bios until OS is loaded. I noticed I couldn't switch between Windows 10 and Mac OS by holding "alt" during startup since I switched to corsair RGB K70 Mk.2 - FWIW I have the corsair supported program on the windows 10 and the CKB 3.12 on the mac partition. IDK if this is a bug or feature request, but I used a different wired usb keyboard and the alt key was recognized as being held down during boot.

**Comment by ZirconiumX** [comment]
I have a hunch about this. Corsair use a nonstandard USB endpoint configuration for their keyboards, and perhaps the Apple EFI doesn't recognise it because normal Apple keyboards use the standard endpoint configuration.

So let's try using BIOS mode on your keyboard. When you boot up, hold winlock and F1 for about three seconds and release, which should make your scroll lock light blink if you did it correctly. Then try holding alt.

Hopefully you still have time left in the EFI to press alt.

**Comment by tatokis** [comment]
Closing due to lack of reply from OP

**Comment by mattbehnken** [comment]
Thank you, I missed the reply email from 22 days ago. I'll try that today, very  much appreciate any tips. Currently I have another keyboard tucked away but still plugged via usb for switching back to mac os (alt during boot), will circle back.e
