### ISSUE TITLE
Shift+scroll issue on macOS Sierra and Mojave

### ISSUE THREAD

**Issue by jacc** [ckb-next/ckb-next#299]
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2611749/ckb-next-dev-detect-report.gz)

Hey everyone. I just got a K95 RGB Plat and a M65 Pro for Black Friday today. I noticed some really weird behavior from the keyboard and mouse, and was wondering if it was a driver issue or not.

In games, (especially Fortnite), I cannot scroll whilst holding shift. After some googling, I noticed that this seems to be a Mac feature that can not be disabled. I never had this problem with my Steelseries mouse. Is there something that I can enable in the current version to fix this, or am I out of luck here?

Thank you!

All the best,
Jack

Edit @ 7:36pm EST - Just realized the same thing is happening on Mojave. I was hoping it might have been a driver thing but it is in fact an OS thing.

**Comment by tatokis** [comment]
Sorry, I missed you earlier when you got on IRC.
Holding down shift and scrolling, actually scrolls horizontally instead of vertically, which is what I believe the issue is.

It is possible the steelseries driver has a workaround for it.
I asked someone with a magic mouse to verify what the behaviour is when scrolling horizontally and vertically with shift held down, to see if it is possible to implement a workaround to always scroll vertically with shift held down.

Unfortunately, if the aforementioned workaround isn't possible, I don't think there's much else we can do, as this also happens without ckb installed.

**Comment by jacc** [comment]
How does the SteelSeries driver have the workaround then? Would there be a way to completely disable vertical scrolling through somewhere in the Mac? This is kind of a deal breaker for me.

**Comment by tatokis** [comment]
So, after testing, I have some bad and some good news.

The bad news is that the workaround I was thinking of implementing in the driver is impossible, so unfortunately there is nothing we can do.

macOS does in fact not have an option to disable this behaviour.
In order to disable shift from scrolling horizontally, one has to capture the scroll events, modify them to remove the shift modifier and send them back to the OS.

This is out of the scope of this driver, as we send input events at a much lower level.

The good news is that with something like https://mos.caldis.me/ (I tested version 2.3.0.) you can enable "smooth scrolling", set the sliders all the way down, and under "advanced" set Shift key to disabled.
