### ISSUE TITLE
Add Corasir RGB Memory Support

### ISSUE THREAD

**Issue by TheBrokenRail** [ckb-next/ckb-next#316]
# Feature request

## What is the program's current behavior?
It does not detect Corsair RGB RAM.

## What would you like it to do instead?
Detect and control RGB RAM.

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2704663/ckb-next-dev-detect-report.gz)

**Comment by CalcProgrammer1** [comment]
Might be out of the scope of this project.  RGB RAM is not interfaced via USB, unlike keyboards, mice, mouse mats, etc.  Instead, RAM module RGB controllers connect via the SMBus interface.  I've got my own project where I'm working to reverse engineer ASUS Aura lighting on motherboards.  The Aura controllers on most motherboards use SMBus as well, and many of the available RGB RAM modules use an Aura-protocol compatible controller.  Corsair RGB RAM does not, but since I already was working on SMBus and RGB RAM I picked up a Corsair Vengeance RGB stick to reverse engineer.  I plan on supporting them in my project and already have the commands figured out for basic color and breathing mode control.

Issue on my project for tracking RGB RAM reverse engineering progress:

https://gitlab.com/CalcProgrammer1/OpenAuraSDK/issues/8#note_148771861

I plan on continuing to pick up other RGB RAM modules as well if I find them cheap on eBay.

**Comment by tatokis** [comment]
I have reverse engineered the protocol for the RAM and have also created some software for it. I just haven't published it due to lack of time

**Comment by esion-net** [comment]
@tatokis Since I got a new pc with those RAM running on linux - Any plans to publish it anytime soon? :)

**Comment by bitcharmer** [comment]
> I have reverse engineered the protocol for the RAM and have also created some software for it. I just haven't published it due to lack of time

It's been 4 years now. Can you please share what you have so someone else can pick this up?

**Comment by gravityfargo** [comment]
Closing this in favor of #589 since a specific model was listed.
