### ISSUE TITLE
[Feature Request]Allow more character in Binding/Typing

### ISSUE THREAD

**Issue by marema31** [ckb-next/ckb-next#407]
I found ckb-next when I tried to resolved a annoying problem with my azerty corsair keyboard on macOS: when I use the < key (near the left shift key) I obtain the ² characters.

I love the abilities ckb-next provides but it missing just a small addition to correct the problem, on the typing select list of binding pane could you please add the < character ?

Regards

**Comment by tatokis** [comment]
Apologies for the late response. Unfortunately that's not really possible. ckb-next works on a lower level than key codes.

It does not tell macOS which character (such as `<`) was pressed, but which physical key on the keyboard.
The issue you are having is because of the layout you have selected in macOS. If you can find another key that can produce the character you want, you may be able to solve it that way.

Alternatively, try going through the macOS keyboard autodetection to see if that helps, and make sure you have the correct layout set in macOS.
