### ISSUE TITLE
Please add this to the various Linux repositories?

### ISSUE THREAD

**Issue by CHJ85** [ckb-next/ckb-next#461]
Hi there. I'm a Ubuntu user. Would be nice having this in the actual repo.
Because this is such an important program it should be easily available for people.

**Comment by ZirconiumX** [comment]
We intentionally avoid being in repositories where possible because our development model is fundamentally incompatible with it; we roll fixes and new device features into a new release, instead of backporting them to older "stable" releases. It results in less maintenance overhead, just like being a user-space driver instead of a kernel-space driver.

**Comment by CHJ85** [comment]
Ah, I see. That makes sense.
Well. Could you at least provide a DEB package?

**Comment by ZirconiumX** [comment]
The community provides those; there's a PPA for it I think. We just build from source.

**Comment by CHJ85** [comment]
Ok thank you :+1:
