### ISSUE TITLE
[macos-Catalina]System Extension is not allowed; no prompt and no option

### ISSUE THREAD

**Issue by Ketenks** [ckb-next/ckb-next#516]
[ckb-next-report-1576826540.gz](https://github.com/ckb-next/ckb-next/files/3987186/ckb-next-report-1576826540.gz)

### Source
How and where did you get this program, e.g.:
  * Pre-built dmg for macOS

## Logs & crash reports

Attach:
report is attached

## What is the program's current behaviour?
devices are not recognized
## Any other notes & comments?
-In Security and Privacy
ckb-next has Full Disk Access
ckb-next has Input Monitoring

**Comment by tatokis** [comment]
Make sure `ckb-next-daemon` has input monitoring, not `ckb-next`

**Comment by Ketenks** [comment]
I haven't been able to find it in the Security and Privacy options. That was all I got when I went to give those permissions. Am I supposed to 'Show Package Contents' in order to find it? I would figure there would be a prompt for it at least and in my case there wasn't.

During the installation it had permission problems that the 'Install.app' had authority over and it could not finish the installation normally but it went through it anyway and then left me with the two messages: "System Extension is not allowed" and "CKB-Next-Daemon needs input monitoring in Security and Privacy" but when I went there to give it those permissions neither of those programs were options.

**Comment by jaspermutsaerts** [comment]
Today I got the same problem after upgrading to Catalina. But I found a workaround!
Couldn't add the daemon to Input Monitoring because when there are no apps in the list, it's not possible to manually add them. Only apps can add the first one.
So I decided to write a Swift simple command line app that does nothing else than trigger the dialog and itself to the list so there is an entry. For those without Xcode I converted it to an actual app. 

[Download Empty Input Monitoring Entry app ](https://github.com/ckb-next/ckb-next/files/5091404/Empty.Input.Monitoring.Entry.zip)

**Screenshots**
<img width="444" alt="Screen Shot 2020-08-18 at 17 38 38" src="https://user-images.githubusercontent.com/6190853/90535340-16ebca80-e17b-11ea-8dba-3c65a3bac8ef.png">
<img width="396" alt="Screen Shot 2020-08-18 at 17 41 36" src="https://user-images.githubusercontent.com/6190853/90535420-29660400-e17b-11ea-99ec-57475f0bf2c9.png"><img width="444" alt="Screen Shot 2020-08-18 at 17 41 45" src="https://user-images.githubusercontent.com/6190853/90535395-2408b980-e17b-11ea-9498-e1b5ce8a42e1.png">
<img width="585" alt="Screen Shot 2020-08-18 at 17 41 54" src="https://user-images.githubusercontent.com/6190853/90535433-2c60f480-e17b-11ea-9a11-5753f74ebd26.png">
<img width="585" alt="Screen Shot 2020-08-18 at 17 42 12" src="https://user-images.githubusercontent.com/6190853/90535437-2e2ab800-e17b-11ea-9507-3cc8214b850e.png">
<img width="585" alt="Screen Shot 2020-08-18 at 18 04 04" src="https://user-images.githubusercontent.com/6190853/90537140-3edc2d80-e17d-11ea-8e4b-a2bbcf134105.png">



**Used Code**
Used code based on https://developer.apple.com/videos/play/wwdc2019/701/ 
I didn't actually see the video throughout, but considered this code shown harmless.

```swift
import Foundation

func callback(
    proxy: CGEventTapProxy,
    type: CGEventType,
    event: CGEvent,
    userInfo: UnsafeMutableRawPointer?
) ->Unmanaged<CGEvent>? {
    // don't really do anything
    return nil
}

// Register to listen to tapEvents: this will trigger an  input monitoring dialog
let eventMask:CGEventMask = 1 << CGEventType.keyDown.rawValue
let eventTap = CGEvent.tapCreate(
    tap: .cghidEventTap,
    place: .tailAppendEventTap,
    options: .listenOnly,
    eventsOfInterest: CGEventMask(eventMask),
    callback: callback,
    userInfo: nil
)
```

**Disclamer**:
Use at own risk. It did resolve this exact problem for me. Of course it's still just a workaround.
