### ISSUE TITLE
ppc64be support

### ISSUE THREAD

**Issue by AbsyntheSyne** [ckb-next/ckb-next#59]
# Bug report

- [x] Yes
- [ ] No

## General information
Built fine for PowerPC G5. I dunno if you intended for it to be built on ppc but.. well, it built lol. That's about it, though. CPU is 970MP, it's PowerPC 64-bit

### Source
built manually using ./quickinstall

### Branch
master
## Logs & crash reports `ckb-daemon`:
Uploaded here.
[ckb-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/1650448/ckb-dev-detect-report.gz)

## What is the program's current behavior?
Broken, I guess?

## What is the expected behavior of the program?
Not break my system haha

## Any other notes & comments?
I understand this is uncharted territory for most people, but I would absolutely appreciate it so much if you could get this working. I'd be willing to help with my PowerMac :)

**Comment by ZirconiumX** [comment]
Hah, a G5! A man after my own heart. I had a G3 and G4 as a kid. Think I still have the G4, actually.

I would bet it's due to the codebase making large assumptions about the platform, from [unaligned access](https://github.com/ckb-next/ckb-next/blob/master/src/ckb-daemon/dpi.c#L166-L167), to [no endian awareness](https://github.com/ckb-next/ckb-next/blob/master/src/ckb-daemon/usb_linux.c#L77), to even making assumptions about the type of `char` (which I [had to fix](https://github.com/mattanger/ckb-next/pull/266)).

If anything is going to help make the code more portable, it's a guy with a G5.

**Comment by AbsyntheSyne** [comment]
Good luck :) Lemme know if you need me to test anything. I'll be in the IRC channel.

**Comment by ZirconiumX** [comment]
As a reference, #76 should help fix some crashing, if not all of it.

**Comment by ZirconiumX** [comment]
Due to the relative scarcity of big-endian devices nowadays, hardcoded endian dependencies in the code and lack of hardware to test on, we've decided we're not going to support this.
