### ISSUE TITLE
Share state of modifier keys with all connected keyboards

### ISSUE THREAD

**Issue by Mexflubber** [ckb-next/ckb-next#640]
## What is the program's current behaviour?
When I press a modifier key on my keyboard (shift) and one of my mouse's button I do not get Shift + button. I only get one of them.

## What would you like it to do instead?
Share keys pressed and combine Shift + button on mouse.

## Any other notes & comments?
[Karabiner handles this use case](https://karabiner-elements.pqrs.org/docs/manual/misc/implicit-behavior/). Could we have it in CKB ??

**Comment by tatokis** [comment]
There is an option in the settings tab if I recall correctly that enables sharing modifiers. Unfortunately, due to how ckb works, it requires having both a mouse and keyboard managed by ckb to share the modifiers.
Karabiner can work around it because it's a generic hid driver and can manage all input devices, whereas ckb can only manage corsair devices (that are supported).
