### ISSUE TITLE
Failed to start ckb-next-daemon.service: Unit ckb-next-daemon.service is masked.

### ISSUE THREAD

**Issue by guzi-momma** [ckb-next/ckb-next#793]
i have used the recommend solution that pops up when opening the application and i can not get this to work

**Comment by alvesvaren** [comment]
Try unmasking it with `sudo systemctl unmask ckb-next-daemon`

**Comment by MaoMaoCake** [comment]
Can we have this added to the wiki as part of the installation step? This should help newbies to actually get it to work.

**Comment by tatokis** [comment]
I don't know why this is happening, however if you're seeing this with the packages from the ubuntu/debian repositories (instead of the PPA), you should open a bug there instead. We do not provide support for these packages.

That said, I'll add the unmask command in the instructions and in the packaging for the PPA. Running it when it's not needed won't harm.
