### ISSUE TITLE
Corsair M65 RGB Elite don't work on mousepad

### ISSUE THREAD

**Issue by d3m0-sm** [ckb-next/ckb-next#828]
I use a M65 RGB Elite and have installes the newest version of cbk-next on Kubuntu 20.04.

If i use my M65 on my mousepad, the corsair won't move after login. The Optical Sensor works just fine on Windows. 

In DirectX the mouse is shown up with the drivers of cbk-next

**Comment by ovandermeer** [comment]
I'm having the same issues with my M65 RGB Elite, and a temporary fix seems to be setting the "lift height" to the highest option. You'll need to connect another (non-corsair) mouse to your pc, because as far as I can tell there's no easy way to change the setting without one. To change the mouse height, launch the ckb-next software, go to the M65 RGB Elite tab, go to "Performance", and change "Lift height" in the bottom right to "High". Unfortunately this setting flips back whenever you change modes or create a new mode, so it's not an ideal solution.

**Comment by tatokis** [comment]
How many Lift Height options does this mouse have in iCUE?

**Comment by d3m0-sm** [comment]
Thx ovandermeer. Thas solved the Problem
