### ISSUE TITLE
No devices connected, but I have a K70 RGB Pro

### ISSUE THREAD

**Issue by adocampo** [ckb-next/ckb-next#915]
### Affected Devices

K70 RGB Pro

### Linux Distribution

Arch

### Installation Method

AUR

### ckb-next version

ckb-next-0.5.0

### What did you expect?

The GUI should show my keyboard and let me configure it.

### Did you try anything that may have helped?

I've rebooted the computer to see if that helped, but no.

### Additional Details

Add any additional details here.

### Generated Report

Drag your generated report here.
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/10300624/ckb-next-dev-detect-report.gz)

**Comment by mnbnd** [comment]
I have the same issue. It doesn't get detected in OpenRGB both on Windows or Linux if that helps as well.

[ckb-next-report-1672011479.gz](https://github.com/ckb-next/ckb-next/files/10300778/ckb-next-report-1672011479.gz)

**Comment by Theymoon** [comment]
I reported the same issue half a year ago (https://github.com/ckb-next/ckb-next/issues/865) but it still doesn't work.

I see that @gravityfargo added K70 RGB Pro to the to-do list some time ago (https://github.com/ckb-next/ckb-next/issues/896), but maybe didn't find the time yet.

Here is an updated report as I updated the system (Debian Sid) several times since my first report.

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/10474241/ckb-next-dev-detect-report.gz)

**Comment by gravityfargo** [comment]
Duplicate of #865
